# Generated by Django 4.2.4 on 2024-01-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=100)),
                ("topic", models.CharField(blank=True, max_length=50, null=True)),
                ("current_question_index", models.IntegerField(blank=True, null=True)),
                ("score", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "survey_response",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
