# Generated by Django 4.2.4 on 2024-02-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CoinSavvy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
